### ISSUE TITLE
RSS link in HTML <head> returns 404

### ISSUE THREAD

**Issue by simevidas** [sindresorhus/sindresorhus.github.com#17]
https://github.com/sindresorhus/sindresorhus.github.com/blob/main/_layouts/default.html#L41

<img width="1001" alt="Screenshot 2022-05-21 at 15 25 40" src="https://user-images.githubusercontent.com/716405/169653748-56a0c920-e372-46c0-8ab2-04d5b7d21270.png">

<img width="923" alt="Screenshot 2022-05-21 at 15 26 01" src="https://user-images.githubusercontent.com/716405/169653746-e341c0d8-48af-4055-a177-51794b1b53aa.png">

**Comment by sindresorhus** [comment]
Thanks for catching that. Fixed.
