### ISSUE TITLE
Cursor is hidden...difficult to navigate

### ISSUE THREAD

**Issue by braeden123** [sindresorhus/sindresorhus.github.com#6]
Latest Chrome on Ubuntu 18.04 LTS - in incognito too.

Not sure if this is an intended behavior. 

edit: I see in main.scss where you set an emoji cursor, not sure if you can implement a fallback to a normal cursor. I assume my browser isn't supporting it properly.

**Comment by sindresorhus** [comment]
I'll just remove it. Was fun for awhile.
